name: SimplePlugin
main: com.fourh.sample.Main
version: 0.1
api-version: "1.19"

commands:
  remove_floor:
    description: Displays your position or teleports you to another.
    usage: /remove_floor x y z w